/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#ffdbcc",
        "primary-container": "#ff6b00",
        "tertiary": "#006e2f",
        "on-tertiary-fixed": "#002109",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#6bff8f",
        "error-container": "#ffdad6",
        "primary": "#a04100",
        "outline": "#8e7164",
        "secondary": "#555f6f",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-highest": "#d3e4fe",
        "surface": "#f8f9ff",
        "primary-fixed-dim": "#ffb693",
        "on-secondary-container": "#596373",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "outline-variant": "#e2bfb0",
        "on-tertiary-container": "#003a15",
        "tertiary-fixed-dim": "#4ae176",
        "surface-variant": "#d3e4fe",
        "on-primary-container": "#572000",
        "tertiary-container": "#00b050",
        "surface-tint": "#a04100",
        "on-primary-fixed-variant": "#7a3000",
        "inverse-primary": "#ffb693",
        "on-surface": "#0b1c30",
        "surface-container": "#e5eeff",
        "on-secondary-fixed-variant": "#3d4756",
        "surface-container-high": "#dce9ff",
        "surface-container-low": "#eff4ff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#005321",
        "secondary-container": "#d6e0f3",
        "on-primary-fixed": "#351000",
        "secondary-fixed": "#d9e3f6",
        "on-surface-variant": "#5a4136",
        "inverse-surface": "#213145",
        "surface-dim": "#cbdbf5",
        "secondary-fixed-dim": "#bdc7d9",
        "on-background": "#0b1c30",
        "background": "#f8f9ff",
        "on-secondary-fixed": "#121c2a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "24px",
        "stack-lg": "32px",
        "container-max": "1280px",
        "stack-sm": "8px",
        "unit": "4px",
        "stack-md": "16px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "button": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "button": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
